# Generated by Django 3.2.23 on 2024-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20240113_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loses',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=1),
        ),
    ]
