# Generated by Django 4.2.10 on 2024-04-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_chatmessages_id_alter_match_id_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
