# Generated by Django 3.2.23 on 2024-01-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20240113_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(default='/media/default.jpg', upload_to=''),
        ),
    ]
