# node:alpine will be our base image to create this image
FROM node:alpine
# Set the /app directory as working directory
WORKDIR /app
# Install ganache-cli globally
RUN npm install ganache-cli --save-dev && mkdir /data
ENV PATH="/app/node_modules/.bin:${PATH}"
COPY ./entrypoint-ganache.sh /app

EXPOSE 8545

# Set the default command for the image
ENTRYPOINT ["./entrypoint-ganache.sh"]
