FROM python:3.8.9

WORKDIR /app

ADD ./blockchain/requirements.txt .
ADD ./blockchain/entrypoint.sh .

RUN	pip install --upgrade pip && \
pip install -r requirements.txt

ENTRYPOINT [ "./entrypoint.sh" ]