FROM python:3.7

WORKDIR /app

ADD ./frontend/requirements.txt .
ADD ./frontend/entrypoint.sh .
ADD ./certs .

RUN	pip install --upgrade pip && \
	pip install -r requirements.txt 

ENTRYPOINT [ "./entrypoint.sh" ]