FROM python:3.7

WORKDIR /app

ADD ./user_auth/requirements.txt .
ADD ./user_auth/entrypoint.sh .

RUN	pip install --upgrade pip && \
	pip install -r requirements.txt 

ENTRYPOINT [ "./entrypoint.sh" ]