# Generated by Django 3.2.25 on 2024-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(default='/media/default.jpg', upload_to='./media'),
        ),
    ]
