# Generated by Django 3.2.25 on 2024-05-26 00:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240525_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_pic',
            field=models.ImageField(default='default.jpg', upload_to=api.models.user_directory_path),
        ),
    ]
