# Generated by Django 3.2.25 on 2024-05-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_prof_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prof_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
    ]
